name: Build, Test and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm test
        env:
          MONGO_URI: mongodb://localhost:27017/prehranko_test
          OPENAI_API_KEY: dummy_key_for_testing

  test-orv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r ORV/requirements.txt
          pip install pytest gdown

      - name: Run ORV tests
        run: |
          cd ORV
          pytest tests

  build-and-push:
    needs: [test-backend, test-orv]  # Čaka na oba testa
    runs-on: ubuntu-latest

    strategy:
      matrix:
        component:
          - name: backend
            context: .
            dockerfile: ./Dockerfile
            tag: martinferk/prehranko-backend:latest

          - name: mqtt-backend
            context: ./NPO/MQTT
            dockerfile: ./NPO/MQTT/Dockerfile
            tag: martinferk/prehranko-mqtt-backend:latest

          - name: orv
            context: ./ORV
            dockerfile: ./ORV/Dockerfile
            tag: martinferk/prehranko-orv:latest

          - name: frontend
            context: ./RAZI/frontend
            dockerfile: ./RAZI/frontend/Dockerfile
            tag: martinferk/prehranko-frontend:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push ${{ matrix.component.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.dockerfile }}
          push: true
          tags: ${{ matrix.component.tag }}
